#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

service_data() {
	/usr/bin/zerokvm --version
}

start_service() {
	modprobe libcomposite
	if ! grep -qE '\s/sys/kernel/config\s+configfs\s' /proc/mounts; then
		mount -t configfs none /sys/kernel/config
	fi

	procd_open_instance
	procd_set_param command /usr/bin/zerokvm -l "[::]:80" -l "[::]:443,tls" --https-redirect --cert /etc/uhttpd.crt --cert-key /etc/uhttpd.key -p /:https://127.0.0.1:8443/
	procd_set_param pidfile /var/run/zerokvm.pid
	procd_set_param term_timeout 3
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 5 1 5
	procd_close_instance
}
