#!/bin/sh
set -e

to_byte_array() {
	printf '['
	xxd -i || return 1 | sed 's/ //g; s/,$//'
	printf ']'
}

{
	cat <<EOF
// <auto-generated/>
namespace ZeroKvm;
internal static partial class Wwwroot {
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
	private static partial byte[] GetAssetsArchive()
	{
		return
EOF
	(
		cd wwwroot || exit 1
		tar -cz --numeric-owner --exclude '*/.*' * || exit 1
	) | to_byte_array || exit 1
	cat <<EOF
;
	}
}
EOF
} > ./obj/wwwroot.g.cs
