FROM mcr.microsoft.com/dotnet/sdk:10.0-noble-aot-arm64v8 AS build
ENV DEBIAN_FRONTEND=noninteractive
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
RUN apt update && apt install -y \
    xxd \
    libaio-dev \
    libturbojpeg0-dev
COPY . /src
WORKDIR /src
RUN dotnet publish -r linux-arm64 ./ZeroKvm/ZeroKvm.csproj -o /out

FROM scratch
COPY --from=build /out/ /linux-arm64
